//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futbol.Models
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class Clasificacion
    {
        public decimal ID { get; set; }
        public Nullable<decimal> POSICION { get; set; }
        public Nullable<decimal> EQUIPO { get; set; }
        public Nullable<decimal> GOLES { get; set; }
        public Nullable<decimal> PUNTOS { get; set; }
    
        public virtual Equipos EQUIPOS { get; set; }
    }
}
