//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futbol.Models
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class Jugadores_Mapping : EntityTypeConfiguration<Jugadores>
    {
        public Jugadores_Mapping()
        {					
    		this.HasKey(t => t.ID);		
    		this.ToTable("JUGADORES", "PROTOCOLO");
    		this.Property(t => t.ID).HasColumnName("ID");
    		this.Property(t => t.NOMBRE).HasColumnName("NOMBRE").IsUnicode(false).HasMaxLength(100);
    		this.Property(t => t.APELLIDOS).HasColumnName("APELLIDOS").IsUnicode(false).HasMaxLength(200);
    		this.Property(t => t.F_NACIMIENTO).HasColumnName("F_NACIMIENTO");
    		this.Property(t => t.POSICION).HasColumnName("POSICION").IsUnicode(false).HasMaxLength(100);
    		this.Property(t => t.EQUIPO).HasColumnName("EQUIPO");
    		this.Property(t => t.IMAGEN).HasColumnName("IMAGEN").IsUnicode(false).HasMaxLength(200);
    		this.HasOptional(t => t.EQUIPOS).WithMany(t => t.JUGADORES).HasForeignKey(d => d.EQUIPO);
    	}
    }
}

